name: Flashstep Microlearner
description: "The frontend of the entire project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: any

  http: ^1.6.0
  flutter_secure_storage: ^9.2.4
  uuid: ^4.5.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.4

  build_runner: 2.4.13
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/LogoWIthoutText_WithoutBG.png
    - assets/LogoWithoutText_WhiteBackground.png
    - assets/LogoWithText.png
    - assets/LogoWithoutText_WithoutBGLarge.png
    - assets/LogoWithText_WithoutBG.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/LogoWithoutText_WithoutBGLarge_Square.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/LogoWithoutText_WithoutBGLarge_Square.png"
  adaptive_icon_foreground_inset: 16
  adaptive_icon_monochrome: "assets/LogoWithoutText_WithoutBGLarge_Square_Monochrome.png"