name: frontend
description: "The frontend of the entire project"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.6.1
  bloc: ^9.2.0
  flutter_bloc: ^9.1.1
  drift: ^2.18.0
  sqlite3_flutter_libs: ^0.5.0
  path_provider: ^2.1.5
  path: any

  http: ^1.6.0
  flutter_secure_storage: ^9.2.4

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: 2.4.13
  drift_dev: ^2.18.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/app_logo.png