services:
  - type: web
    name: flashstep-api
    runtime: docker
    plan: free
    region: singapore
    branch: main
    rootDir: backend
    dockerfilePath: ./backend/deployments/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /health
    autoDeployTrigger: checksPass
    envVars:
      - key: DB_HOST
        sync: false
      - key: GO_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_SSLMODE
        value: require
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRY_MINUTES
        value: "120"