services:
  postgres:
    image: postgres:16-alpine
    container_name: flashcards_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-flashcards}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../migrations/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql:ro
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-flashcards}"]
    #   interval: 130s
    #   timeout: 10s
    #   retries: 20
    #   start_period: 120s

  app:
    build:
      context: ..
      dockerfile: deployments/Dockerfile
    container_name: flashcards_backend
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "8080:8080"
    # depends_on:
    #   postgres:
    #     condition: service_healthy

volumes:
  postgres_data:
